# Generated by Django 3.2.16 on 2024-07-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('пользователь', 'пользователь'), ('админ', 'админ'), ('модератор', 'модератор'), ('суперпользователь', 'суперпользователь')], default='пользователь', max_length=17, verbose_name='Роль'),
        ),
    ]
