# Generated by Django 3.2.16 on 2024-07-17 17:41

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ('username', 'id'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('moderator', 'moderator'), ('superuser', 'superuser')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.username_validator]),
        ),
    ]
