# Generated by Django 3.2.16 on 2024-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_apiuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('moderator', 'moderator'), ('superuser', 'superuser')], default='user', max_length=9, verbose_name='Роль'),
        ),
    ]
