# Generated by Django 3.2.16 on 2024-07-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240711_2352'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title_and_author',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review_author'),
        ),
    ]
