# Generated by Django 3.2.16 on 2024-07-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240710_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(default='XXXX', max_length=255, null=True, verbose_name='код подтверждения'),
        ),
    ]
