# Generated by Django 3.2.16 on 2024-07-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240712_0114'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_author',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review'),
        ),
    ]
