# Generated by Django 3.2.16 on 2024-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
